# Site settings
title: crossprogramming
email:
description: >
  Presenting Jesus Christ to the world using programming skills.
baseurl: ""
url: "https://crossprogramming.com"
twitter_username: satrapu
github_username: satrapu
linkedin_username: bmarian
google_analytics: 
disqus:
  shortname:
  
# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock
